name: tft_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - u8darts==0.39.0
      - numpy==1.26.4
      - pandas
      - matplotlib
      - yfinance
      - jupyterlab
      - ipykernel
