#!/usr/bin/env python3
"""
Create comprehensive analysis notebook
"""

notebook_content = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Prioritized Experience Replay (PER) - Empirische Analyse\n",
                "\n",
                "## CAS AI Workshop - DQN Extensions\n",
                "\n",
                "Dieses Notebook dokumentiert eine umfassende empirische Untersuchung von Prioritized Experience Replay (PER) im Vergleich zu Uniform Replay."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Konzeptionelle Erklärung: Was ist PER?\n",
                "\n",
                "### Motivation\n",
                "\n",
                "Nicht alle Erfahrungen im Replay Buffer sind gleich wertvoll:\n",
                "- **Leichte Samples**: Agent versteht bereits gut → wenig Lerngain\n",
                "- **Schwierige Samples**: Agent ist überrascht → großes Lerngain\n",
                "\n",
                "**Uniform Replay** sampelt alle Experiences mit gleicher Wahrscheinlichkeit.\n",
                "**Prioritized Replay** sampelt wichtige Experiences häufiger.\n",
                "\n",
                "### Prioritätsdefinition\n",
                "\n",
                "Priorität basiert auf **TD-Error** (Temporal Difference Error):\n",
                "\n",
                "$$p_i = (|TD_i| + \\epsilon)^\\alpha$$\n",
                "\n",
                "wobei:\n",
                "- $TD_i = r_i + \\gamma \\max_{a'} Q(s', a') - Q(s, a)$ (Überraschung)\n",
                "- $\\alpha \\in [0, 1]$ kontrolliert Prioritäts-Strength\n",
                "- $\\epsilon$ verhindert Zero-Priority für erneute Samples"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Replay Buffer Mechanik\n",
                "\n",
                "### Uniform Replay Buffer\n",
                "\n",
                "```python\n",
                "class UniformReplayBuffer:\n",
                "    def __init__(self, capacity):\n",
                "        self.buf = deque(maxlen=capacity)  # FIFO\n",
                "    \n",
                "    def add(self, s, a, r, s2, done):\n",
                "        self.buf.append((s, a, r, s2, done))\n",
                "    \n",
                "    def sample(self, batch_size):\n",
                "        batch = random.sample(self.buf, batch_size)  # Uniform\n",
                "        return batch\n",
                "```\n",
                "\n",
                "**Eigenschaften:**\n",
                "- O(1) Insert\n",
                "- O(1) Sample (mit Indexing)\n",
                "- Speicher: O(N)\n",
                "- Keine Prioritäts-Updates\n",
                "\n",
                "### Prioritized Replay Buffer (mit SumTree)\n",
                "\n",
                "```python\n",
                "class PrioritizedReplayBuffer:\n",
                "    def __init__(self, capacity, alpha):\n",
                "        self.tree = SumTree(capacity)  # Binärbaum\n",
                "        self.alpha = alpha\n",
                "    \n",
                "    def add(self, s, a, r, s2, done, priority):\n",
                "        self.tree.add(priority^alpha, data)  # Log-Update\n",
                "    \n",
                "    def sample(self, batch_size, beta):\n",
                "        # Stratified sampling mit Importance Weights\n",
                "        batch = stratified_sample(self.tree, batch_size)\n",
                "        weights = (1 / (N * P(i)))^beta  # IS-Korrektur\n",
                "        return batch, weights\n",
                "```\n",
                "\n",
                "**Eigenschaften:**\n",
                "- O(log N) Insert\n",
                "- O(log N) Sample\n",
                "- O(log N) Priority Update\n",
                "- Speicher: O(N) für Tree + O(N) für Data"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Importance Sampling Correction\n",
                "\n",
                "### Problem mit Prioritized Sampling\n",
                "\n",
                "Wenn wir Samples mit höherer Wahrscheinlichkeit sampeln, ändern wir die Verteilung:\n",
                "- **Uniform Sampling**: P(i) = 1/N für alle i\n",
                "- **Prioritized Sampling**: P(i) ∝ p_i\n",
                "\n",
                "Dies biased die Gradienten-Schätzung! Lösung: Importance-Sampling Weights\n",
                "\n",
                "### Gewichtungsformel\n",
                "\n",
                "$$w_i = \\left( \\frac{1}{N \\cdot P(i)} \\right)^\\beta$$\n",
                "\n",
                "wobei:\n",
                "- $\\beta \\in [0, 1]$ interpoliert zwischen uniform (β=0) und unbiased (β=1)\n",
                "- $N$ = Buffer Size\n",
                "- $P(i)$ = Sampling-Wahrscheinlichkeit\n",
                "\n",
                "### Praktische Implementierung\n",
                "\n",
                "```python\n",
                "# Im Training\n",
                "probs = priorities / sum(priorities)\n",
                "weights = (1 / (N * probs)) ** beta\n",
                "weights = weights / max(weights)  # Normalize\n",
                "\n",
                "# Loss mit Weights\n",
                "loss = mean(weights * td_error^2)\n",
                "```"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Experimentelles Setup\n",
                "\n",
                "### Environment\n",
                "- **LunarLander-v3** (Gymnasium)\n",
                "- State: [x, y, vx, vy, angle, angular_velocity, left_leg, right_leg] (8 dims)\n",
                "- Actions: 0=Idle, 1=Left Engine, 2=Right Engine, 3=Main Engine (4 actions)\n",
                "- Reward: Negative distance to goal, fuel cost, crash penalty\n",
                "- Goal: Return > 200 (soft landing)\n",
                "\n",
                "### Hyperparameter\n",
                "```\n",
                "TOTAL_STEPS = 300,000\n",
                "BATCH_SIZE = 256\n",
                "BUFFER_SIZE = 200,000\n",
                "LEARNING_RATE = 2e-3\n",
                "GAMMA = 0.99  # Discount factor\n",
                "TAU = 0.005   # Soft update target network\n",
                "\n",
                "EPS_START = 1.0\n",
                "EPS_END = 0.05\n",
                "EPS_DECAY = 30,000 steps\n",
                "\n",
                "# PER Specific\n",
                "PER_ALPHA = 0.4  # Reduced for stability\n",
                "PER_BETA_START = 0.4\n",
                "PER_BETA_END = 1.0\n",
                "PER_BETA_STEPS = 60,000\n",
                "```\n",
                "\n",
                "### Evaluation\n",
                "- Alle 15,000 Steps\n",
                "- 5 Evaluation Episodes (greedy, no exploration)\n",
                "- Report: Mean ± Std Return"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Trainingsergebnisse"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "import json\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "\n",
                "# Load results\n",
                "with open('results_summary_CORRECTED.json') as f:\n",
                "    results = json.load(f)\n",
                "\n",
                "uniform = results['uniform']\n",
                "per = results['per']\n",
                "\n",
                "# Extract data\n",
                "u_means = np.array(uniform['eval_means'])\n",
                "u_stds = np.array(uniform['eval_stds'])\n",
                "u_steps = np.array(uniform['eval_steps'])\n",
                "\n",
                "p_means = np.array(per['eval_means'])\n",
                "p_stds = np.array(per['eval_stds'])\n",
                "p_steps = np.array(per['eval_steps'])\n",
                "\n",
                "# Print summary\n",
                "print('='*60)\n",
                "print('ERGEBNISSE: Uniform Replay vs. PER')\n",
                "print('='*60)\n",
                "print(f'\\nUniform Replay:')\n",
                "print(f'  Final: {u_means[-1]:.2f} ± {u_stds[-1]:.2f}')\n",
                "print(f'  Max:   {np.max(u_means):.2f}')\n",
                "print(f'  Mean:  {np.mean(u_means):.2f} ± {np.std(u_means):.2f}')\n",
                "print(f'\\nPrioritized Experience Replay:')\n",
                "print(f'  Final: {p_means[-1]:.2f} ± {p_stds[-1]:.2f}')\n",
                "print(f'  Max:   {np.max(p_means):.2f}')\n",
                "print(f'  Mean:  {np.mean(p_means):.2f} ± {np.std(p_means):.2f}')\n",
                "print(f'\\nDifferenz (PER - Uniform):')\n",
                "print(f'  Final: {p_means[-1] - u_means[-1]:+.2f}')\n",
                "print(f'  Percent: {((p_means[-1] - u_means[-1]) / abs(u_means[-1]) * 100):+.1f}%')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 6. Visualisierungen"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "# Main comparison with confidence bands\n",
                "fig, ax = plt.subplots(figsize=(14, 8))\n",
                "\n",
                "ax.plot(u_steps, u_means, 'o-', color='#1f77b4', label='Uniform Replay', linewidth=3, markersize=8)\n",
                "ax.fill_between(u_steps, u_means - u_stds, u_means + u_stds, color='#1f77b4', alpha=0.2)\n",
                "\n",
                "ax.plot(p_steps, p_means, 's-', color='#ff7f0e', label='PER', linewidth=3, markersize=8)\n",
                "ax.fill_between(p_steps, p_means - p_stds, p_means + p_stds, color='#ff7f0e', alpha=0.2)\n",
                "\n",
                "ax.axhline(y=0, color='gray', linestyle='--', alpha=0.5)\n",
                "ax.set_xlabel('Training Steps', fontsize=12, fontweight='bold')\n",
                "ax.set_ylabel('Evaluation Return', fontsize=12, fontweight='bold')\n",
                "ax.set_title('Performance Comparison: Uniform Replay vs. PER', fontsize=14, fontweight='bold')\n",
                "ax.grid(True, alpha=0.3)\n",
                "ax.legend(fontsize=12)\n",
                "plt.tight_layout()\n",
                "plt.savefig('comparison.png', dpi=150)\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 7. Beobachtungen & Überraschungen\n",
                "\n",
                "### Überraschender Fund: Uniform Replay ist stabiler!\n",
                "\n",
                "**Erwartung:** PER sollte besser sein (höhere Rewards)\n",
                "**Beobachtung:** Uniform Replay zeigt konsistentere Performance\n",
                "\n",
                "### Hypothesen für dieses Phänomen:\n",
                "\n",
                "#### 1. **LunarLander ist relativ einfach**\n",
                "- Uniform Sampling meist ausreichend\n",
                "- PER vorteilhaft erst bei komplexeren Tasks (z.B. Atari)\n",
                "\n",
                "#### 2. **PER ist hyperparameter-sensitiv**\n",
                "- Alpha=0.4 könnte suboptimal sein\n",
                "- Beta-Schedule könnte besser tuned werden\n",
                "- Zu aggressive Priorisierung → Instabilität\n",
                "\n",
                "#### 3. **Sampling Bias bleibt trotz Importance Weights**\n",
                "- Häufig-gesampelte Transitions können overfit werden\n",
                "- Importance-Sampling Correction ist nur asymptotisch unbiased\n",
                "\n",
                "#### 4. **TD-Error basierte Prioritäten können oszillieren**\n",
                "- Early in training: alle TD-Errors sind groß\n",
                "- Später: TD-Error wird noisy wenn Agent am Limit ist\n",
                "- Kann zu Oversampling von \"edge cases\" führen\n",
                "\n",
                "### Beobachtete Muster:\n",
                "\n",
                "1. **Beide Methoden lernen:** Rewards steigen über Zeit\n",
                "2. **Uniform stabiler:** Niedrigere Varianz zwischen Evaluationen\n",
                "3. **PER volatiler:** Höhere Spitzen und Täler\n",
                "4. **Keine dominante Methode:** Abhängig von Punkt im Training"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 8. Statistische Analyse"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "from scipy import stats\n",
                "\n",
                "# T-Test\n",
                "t_stat, p_value = stats.ttest_ind(p_means, u_means)\n",
                "\n",
                "print('T-TEST: Sind die Mittelwerte signifikant unterschiedlich?')\n",
                "print(f'  t-statistic: {t_stat:.4f}')\n",
                "print(f'  p-value: {p_value:.6f}')\n",
                "print(f'  Signifikant (α=0.05)? {\"Ja\" if p_value < 0.05 else \"Nein\"}')\n",
                "\n",
                "# Effect size (Cohen's d)\n",
                "cohens_d = (np.mean(p_means) - np.mean(u_means)) / np.sqrt((np.std(p_means)**2 + np.std(u_means)**2) / 2)\n",
                "print(f'\\nCohen\\'s d (Effektgröße): {cohens_d:.3f}')\n",
                "if abs(cohens_d) < 0.2:\n",
                "    effect = 'Minimal'\n",
                "elif abs(cohens_d) < 0.5:\n",
                "    effect = 'Klein'\n",
                "elif abs(cohens_d) < 0.8:\n",
                "    effect = 'Mittel'\n",
                "else:\n",
                "    effect = 'Groß'\n",
                "print(f'  Interpretation: {effect}')\n",
                "\n",
                "# Variance comparison\n",
                "u_var = np.var(u_means)\n",
                "p_var = np.var(p_means)\n",
                "f_stat = max(p_var, u_var) / min(p_var, u_var)\n",
                "p_variance = 1 - stats.f.cdf(f_stat, len(p_means)-1, len(u_means)-1)\n",
                "\n",
                "print(f'\\nVARIANZ-TEST (Levene\\'s Test):')\n",
                "print(f'  Uniform Variance: {u_var:.2f}')\n",
                "print(f'  PER Variance: {p_var:.2f}')\n",
                "print(f'  F-statistic: {f_stat:.4f}')\n",
                "print(f'  Signifikant unterschiedlich? {\"Ja\" if p_variance < 0.05 else \"Nein\"}')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 9. Reflexion: Wann hilft PER besonders?\n",
                "\n",
                "### ✓ PER ist ideal für:\n",
                "\n",
                "1. **Komplexe Umgebungen**\n",
                "   - Atari-Spiele (57 actions, complex visual features)\n",
                "   - Robotik mit vielen Freiheitsgraden\n",
                "   - Multi-Agent Settings\n",
                "\n",
                "2. **Sparse oder delayed Rewards**\n",
                "   - Nur wenige erfolgreiche Trajectories\n",
                "   - Große Reward-Gradienten zwischen ähnlichen States\n",
                "   - Z.B. Monte Carlo Tree Search + RL\n",
                "\n",
                "3. **Große Replay Buffer**\n",
                "   - > 1 Millionen Transitions\n",
                "   - Computational cost of O(log N) negligible\n",
                "\n",
                "4. **Heterogene Schwierigkeit**\n",
                "   - Sehr unterschiedliche TD-Errors in Buffer\n",
                "   - Agent sieht mix of easy und hard scenarios\n",
                "\n",
                "### ✗ PER kann problematisch sein in:\n",
                "\n",
                "1. **Einfachen Umgebungen**\n",
                "   - Kontinuierliche Kontrolle mit Richtungssignal\n",
                "   - Diskrete Probleme mit klarem Gradient\n",
                "   - Zu viel Komplexität für zu kleinen Benefit\n",
                "\n",
                "2. **Stabilitäts-kritischen Anwendungen**\n",
                "   - Roboter mit realen Kosten\n",
                "   - Sicherheits-kritische Systeme\n",
                "   - Uniform Replay zuverlässiger\n",
                "\n",
                "3. **Mit unzureichendem Tuning**\n",
                "   - Falsche Alpha/Beta → Instabilität\n",
                "   - Fehlerhafte SumTree-Implementierung\n",
                "   - Fehlende IS-Correction"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 10. Wann wird PER instabil?\n",
                "\n",
                "### Instabilitäts-Szenarien:\n",
                "\n",
                "#### 1. **Zu großes ALPHA (z.B. α ≥ 0.8)**\n",
                "```\n",
                "p_i = (|TD_i| + ε)^0.8\n",
                "```\n",
                "- Extrem starke Priorisierung\n",
                "- Ein paar Samples dominieren Buffer\n",
                "- Kann zu Mode Collapse führen\n",
                "- → Gradient wird spiky, instabiles Training\n",
                "\n",
                "#### 2. **Zu kleines BETA (z.B. β < 0.1)**\n",
                "```\n",
                "w_i = (1 / (N * P(i)))^0.05  # Fast keine Correction!\n",
                "```\n",
                "- Unzureichende Importance-Sampling Correction\n",
                "- Bias in Gradient-Schätzung bleibt\n",
                "- → Training divergiert von optimalen Policy\n",
                "\n",
                "#### 3. **Falsche TD-Error Schätzung**\n",
                "- Initial: Target-Netzwerk sehr schlecht\n",
                "- → Alle TD-Errors sind riesig\n",
                "- → SumTree sampling ist fast uniform anyway!\n",
                "- → Oder: Zu aggressive Gradient-Updates\n",
                "\n",
                "#### 4. **Kleine Batch Sizes (< 32)**\n",
                "- Mit PER: noch höhere Varianz\n",
                "- Wichtige Samples könnten übersampelt werden\n",
                "- → Overfitting auf einzelne trajectories\n",
                "\n",
                "#### 5. **Nicht-stationäre Umgebung**\n",
                "- TD-Errors change dramatically\n",
                "- Priorities werden schnell obsolet\n",
                "- Gradienten können instabil werden"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 11. Nachteile von PER\n",
                "\n",
                "### 1. **Computational Cost**\n",
                "- SumTree: O(log N) vs. O(1) sampling\n",
                "- Bei BUFFER_SIZE=1M: ~20 Operationen pro Sample\n",
                "- Overhead: ~2-3x langsamer als Uniform\n",
                "- Problem für Real-Time Applications\n",
                "\n",
                "### 2. **Hyperparameter Komplexität**\n",
                "- Uniform Replay: Einfach (nur Batch Size)\n",
                "- PER: Alpha, Beta, Beta-Schedule, Epsilon\n",
                "- Jeder Parameter ändert Behavior drastisch\n",
                "- Hyperparameter-Suche wird 10x aufwendiger\n",
                "\n",
                "### 3. **Memory Overhead**\n",
                "- SumTree braucht 2N-1 Knoten\n",
                "- Plus leaf indices für Updates\n",
                "- ~2x Memory von Uniform Replay\n",
                "\n",
                "### 4. **Implementierungs-Komplexität**\n",
                "- SumTree Index-Management subtil\n",
                "- Importance-Sampling Weights richtig implementieren\n",
                "- Priority Updates korrekt zuordnen\n",
                "- Viele Möglichkeiten für Bugs (wir hatten einen!)\n",
                "\n",
                "### 5. **Bias durch Häufiges Sampling**\n",
                "- Wichtige Samples werden häufig gezogen\n",
                "- Können zu Overfitting auf diese führen\n",
                "- IS-Weights sind nur asymptotisch unbiased\n",
                "- Small sample size → bias bleibt\n",
                "\n",
                "### 6. **Nicht für alle Problem-Typen ideal**\n",
                "- Nicht universell besser als Uniform\n",
                "- Stark Problem-abhängig\n",
                "- Falsche Erwartung: \"PER = immer besser\""
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 12. Best Practices & Empfehlungen\n",
                "\n",
                "### Entscheidungsbaum: Wann welche Methode?\n",
                "\n",
                "```\n",
                "Einfache Umgebung (< 50 States, Clear Reward Signal)?\n",
                "  ├─ JA → Verwende UNIFORM REPLAY\n",
                "  │        (Einfach, schnell, robust)\n",
                "  │\n",
                "  └─ NEIN\n",
                "       │\n",
                "       Sparse/Delayed Rewards?\n",
                "       ├─ JA → Verwende PER\n",
                "       │        (Fokus auf \"surprising\" events)\n",
                "       │\n",
                "       └─ NEIN\n",
                "            │\n",
                "            Buffer > 500K transitions?\n",
                "            ├─ JA → Evtl. PER (O(log N) cost negligible)\n",
                "            └─ NEIN → Uniform Replay suffiziert\n",
                "```\n",
                "\n",
                "### Hyperparameter Startpunkte:\n",
                "\n",
                "**PER Baseline:**\n",
                "```\n",
                "PER_ALPHA = 0.4        # Moderate prioritization\n",
                "PER_BETA_START = 0.4   # Start with 60% correction\n",
                "PER_BETA_END = 1.0     # Full correction at end\n",
                "PER_EPS = 1e-6         # Prevent zero-priority\n",
                "```\n",
                "\n",
                "**Wenn zu instabil:**\n",
                "```\n",
                "PER_ALPHA = 0.2        # Reduce to 0.2\n",
                "  + Erhöhe GRAD_CLIP_NORM\n",
                "  + Reduziere LEARNING_RATE\n",
                "```\n",
                "\n",
                "**Wenn zu langsam:**\n",
                "```\n",
                "PER_ALPHA = 0.6        # Increase to 0.6\n",
                "  + Reduziere GRAD_CLIP_NORM (vorsichtig!)\n",
                "```\n",
                "\n",
                "### Monitoring-Metriken:\n",
                "\n",
                "1. **Reward Curve**: Sollte monotoniesch steigen\n",
                "2. **Loss**: Sollte abfallen, dann stabilisieren\n",
                "3. **Gradient Norm**: Sollte nicht explodieren\n",
                "4. **TD-Error Distribution**: Überprüfe auf Mode Collapse\n",
                "5. **Sample Frequencies**: Überprüfe ob ein paar Samples überladen werden"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 13. Zusammenfassung\n",
                "\n",
                "### Key Findings:\n",
                "\n",
                "✓ **PER ist theoretisch elegant**\n",
                "- Fokussiert Training auf schwierige Samples\n",
                "- Gut motiviert aus Information-Theorie\n",
                "\n",
                "✓ **Empirisch: Kontext ist kritisch**\n",
                "- Nicht universell besser\n",
                "- Abhängig von Environment, Buffer Size, Hyperparameter\n",
                "\n",
                "✗ **Uniform Replay oft praktischer**\n",
                "- Robuster\n",
                "- Einfacher zu implementieren\n",
                "- Schneller zu trainieren\n",
                "- Weniger Hyperparameter zu tunen\n",
                "\n",
                "### Best Practice:\n",
                "\n",
                "1. **Start mit Uniform Replay**\n",
                "   - Get a working baseline\n",
                "   - Schnell & zuverlässig\n",
                "\n",
                "2. **Wenn nicht zufrieden:** Evaluiere PER\n",
                "   - Nur wenn clear benefit sichtbar\n",
                "   - Sorgfältiges Hyperparameter-Tuning\n",
                "\n",
                "3. **Monitor kontinuierlich**\n",
                "   - Tracking: Rewards, Loss, Gradient Norms\n",
                "   - Instabilität = Rückkehr zu Uniform\n",
                "\n",
                "### Zukunftsrichtungen:\n",
                "\n",
                "- **Hybrid Approaches**: Beginne mit Uniform, switch zu PER\n",
                "- **Adaptive Alpha**: Lerne α während Training\n",
                "- **Alternative Priorities**: Curiosity, KL-Divergence, etc.\n",
                "- **Rainbow DQN**: Kombiniert PER mit Double Q, Dueling, etc."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

import json
from pathlib import Path

output_dir = Path("/home/isc-den/cas-artificial-intelligence/11_dqn_extensions")
notebook_path = output_dir / "PER_Analysis_Report.ipynb"

with open(notebook_path, 'w') as f:
    json.dump(notebook_content, f, indent=2)

print(f"✓ Notebook saved: {notebook_path}")

