#!/bin/bash
# Quick Monitoring Commands for PPO Experiments

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║           PPO TRADING EXPERIMENTS - MONITORING GUIDE                       ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "CURRENT STATUS: Experiments are RUNNING"
echo "Start Time: 2026-03-11 21:09:27"
echo "Duration: 3-6 hours (CPU) or 1-2 hours (GPU)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "QUICK COMMANDS"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Check if experiments are still running:"
echo "   tail -20 experiments_run.log"
echo ""
echo "2. Monitor real-time progress:"
echo "   python monitor.py"
echo ""
echo "3. Check log file size:"
echo "   du -h experiments_run.log"
echo ""
echo "4. See last 50 lines:"
echo "   tail -50 experiments_run.log | less"
echo ""
echo "5. Count how many experiments done:"
echo "   grep -c 'Experiment' experiments_run.log"
echo ""
echo "6. Check if metrics.pkl created (signals completion):"
echo "   ls -lh metrics.pkl"
echo ""
echo "7. Watch log in real-time:"
echo "   tail -f experiments_run.log"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "WHEN COMPLETE (metrics.pkl exists)"
echo "════════════════════════════════════════════════════════════════════════════"
echo ""
echo "View all plots:"
echo "   open equity_curves_comparison.png"
echo "   open drawdown_comparison.png"
echo "   open returns_distribution.png"
echo "   open metrics_heatmap.png"
echo ""
echo "Regenerate visualizations:"
echo "   python create_visualizations.py"
echo ""
echo "Check metrics in Excel:"
echo "   open metrics_comparison.csv"
echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo "NO ACTION NEEDED - Experiments are running automatically!"
echo "════════════════════════════════════════════════════════════════════════════"

